server:
  port:
    8040
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8040/eureka/
  instance:
    hostname: localhost
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: eureka
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true